# Generated by Django 3.0.5 on 2020-04-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200406_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
